# importance "high_detail": [], "low_detail": []
# keyword   "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []    "error_total": 0
# status  "size": 0, "detail": []   "total": 0
func_suite_assign = [
    {"user": "史京南", "error_total": 0, "total": 0,
     "suites": [
         {"suitename": "业务视图-OAM 应用", "user": "jnshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-原生应用", "user": "jnshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-安全管理", "user": "jnshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-集群管理-资源管理", "user": "jnshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-辅助功能", "user": "jnshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "etcd监控面板", "user": "jnshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []}
     ]
     },
    {"user": "赵晓峰", "error_total": 0, "total": 0,
     "suites": [
         {"suitename": "业务视图-应用管理>模板应用", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-应用管理>组件应用", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>定时任务", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>任务", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "独立视图-Catalog(应用商店)", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-镜像仓库", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-应用商店管理>Operator", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-应用商店管理>模板仓库", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-应用商店管理>应用包管理", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-应用商店管理>应用商店chart/operator支持ip协议过滤", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "独立视图-云边协同应用下发", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-GitOps应用(项目级别)", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
     ]
     },
    {"user": "郑虎林", "error_total": 0, "total": 0,
     "suites": [
         {"suitename": "业务视图-计算组件>部署", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>守护进程集", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>有状态副本集", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>容器组", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>弹性伸缩", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>通用-镜像选择组件", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>通用-容器组表单", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>通用-详情页组件", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>通用-容器组列表", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>通用-局部更新", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>通用-debug", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>gpu", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>通用-取消-阻断性提示", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [], "error_size": 0,
          "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>asm-acp融合", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-配置", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-超售比", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "项目管理-命名空间>命名空间", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "项目管理-命名空间>命名空间概览", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-集群管理-自定义资源", "user": "hlzheng", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
     ]
     },
    {"user": "施源", "error_total": 0, "total": 0,
     "suites": [
         {"suitename": "业务视图-网络>内部路由", "user": "yuanshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-网络>外部路由", "user": "yuanshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-网络>入站规则", "user": "yuanshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-网络管理>域名", "user": "yuanshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-网络管理>证书", "user": "yuanshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-网络管理>子网>calico", "user": "yuanshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-虚拟化", "user": "yuanshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-虚拟化管理", "user": "yuanshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
     ]
     },
    {"user": "王珂", "error_total": 0, "total": 0,
     "suites": [
         {"suitename": "业务视图-网络>负载均衡", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-网络>网络策略", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-网络>alb集成GatewayAPI", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [], "error_size": 0,
          "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-网络管理>负载均衡", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-网络管理>负载均衡器-重构用例", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-网络管理>子网>ovn", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-网络管理>集群网络策略", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-网络管理>外部地址池", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-ovn集群互通管理", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-kubeOVN网络可视化", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-网络管理>网络检测", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
     ]
     },
    {"user": "刘明宇", "error_total": 0, "total": 0,
     "suites": [
         {"suitename": "功能开关", "user": "myliu", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-存储>持久卷声明", "user": "myliu", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-存储管理>持久卷", "user": "myliu", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-存储管理>存储类", "user": "myliu", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-存储管理>分布式存储", "user": "myliu", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-存储管理>本地存储", "user": "myliu", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-存储> 存储桶声明", "user": "myliu", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-存储管理>存储桶", "user": "myliu", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-存储管理>卷快照", "user": "myliu", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
     ]
     }
]
api_suite_assign = [
    {"user": "史京南", "total": 0,
     "suites": [
         {"suitename": "业务视图-OAM 应用", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "业务视图-原生应用", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "平台管理-安全管理", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "平台管理-集群管理-资源管理", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "业务视图-辅助功能", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "etcd监控面板", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>部署", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>守护进程集", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>有状态副本集", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>容器组", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>弹性伸缩", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-镜像选择组件", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-容器组表单", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-详情页组件", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-容器组列表", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-局部更新", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-debug", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>gpu", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-取消-阻断性提示", "user": "hlzheng", "size": 0, "detail": []},
         # {"suitename": "业务视图-计算组件>asm-acp融合", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-配置", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "平台管理-超售比", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "项目管理-命名空间", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "平台管理-集群管理-自定义资源", "user": "hlzheng", "size": 0, "detail": []},
     ]
     },
    {"user": "赵晓峰",
     "total": 0,
     "suites": [
         {"suitename": "业务视图-应用管理>模板应用", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-应用管理>组件应用", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>定时任务", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>任务", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "独立视图-Catalog(应用商店)", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-镜像仓库", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "平台管理-应用商店管理>Operator", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "平台管理-应用商店管理>模板仓库", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "平台管理-应用商店管理>应用包管理", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "平台管理-应用商店管理>应用商店chart/operator支持ip协议过滤", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "独立视图-云边协同应用下发", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-GitOps应用(项目级别)", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-存储>持久卷声明", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>持久卷", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>存储类", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>分布式存储", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>本地存储", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "业务视图-存储> 存储桶声明", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>存储桶", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>卷快照", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>pvc告警相关", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>minio对象存储", "user": "myliu", "size": 0, "detail": []},
     ]
     },
    {"user": "施源", "total": 0,
     "suites": [
         {"suitename": "业务视图-网络>内部路由", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "业务视图-网络>外部路由", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "业务视图-网络>入站规则", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>域名", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>证书", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>子网>calico", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "业务视图-虚拟化", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "平台管理-虚拟化管理", "user": "yuanshi", "size": 0, "detail": []},
     ]
     },
    {"user": "王珂", "total": 0,
     "suites": [
         {"suitename": "业务视图-网络>负载均衡", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "业务视图-网络>网络策略", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "业务视图-网络>alb集成GatewayAPI", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>负载均衡", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>负载均衡器-重构用例", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>子网>ovn", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>集群网络策略", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>外部地址池", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-ovn集群互通管理", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-kubeOVN网络可视化", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>网络检测", "user": "kewang", "size": 0, "detail": []},
     ]
     },
]
ui_suite_assign = [
    {"user": "史京南", "total": 0,
     "suites": [
         {"suitename": "业务视图-OAM 应用", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "业务视图-原生应用", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "平台管理-安全管理", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "平台管理-集群管理-资源管理", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "业务视图-辅助功能", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "etcd监控面板", "user": "jnshi", "size": 0, "detail": []}
     ]
     },
    {"user": "郑虎林", "total": 0,
     "suites": [
         {"suitename": "业务视图-计算组件>部署", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>守护进程集", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>有状态副本集", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>容器组", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>弹性伸缩", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-镜像选择组件", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-容器组表单", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-详情页组件", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-容器组列表", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-局部更新", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-debug", "user": "hlzheng", "size": 0, "detail": []},
         # {"suitename": "业务视图-计算组件>gpu", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-取消-阻断性提示", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>asm-acp融合", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "业务视图-配置", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "平台管理-超售比", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "项目管理-命名空间", "user": "hlzheng", "size": 0, "detail": []},
         {"suitename": "平台管理-集群管理-自定义资源", "user": "hlzheng", "size": 0, "detail": []},
     ]
     },
    {"user": "施源", "total": 0,
     "suites": [
         {"suitename": "业务视图-网络>内部路由", "user": "yuanshi", "size": 0, "detail": []},
         # {"suitename": "业务视图-网络>外部路由", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "业务视图-网络>入站规则", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>域名", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>证书", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>子网>calico", "user": "yuanshi", "size": 0, "detail": []},
         # {"suitename": "业务视图-虚拟化", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "平台管理-虚拟化管理", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "业务视图-网络>负载均衡", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>负载均衡", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>负载均衡器-重构用例", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>子网>ovn", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>集群网络策略", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-ovn集群互通管理", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-kubeOVN网络可视化", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>网络检测", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "业务视图-网络>网络策略", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>外部地址池", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "业务视图-网络>alb集成GatewayAPI", "user": "kewang", "size": 0, "detail": []},
     ]
     },
    {"user": "刘明宇", "total": 0,
     "suites": [
         # {"suitename": "功能开关", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "业务视图-存储>持久卷声明", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>持久卷", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>存储类", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>分布式存储", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>本地存储", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "业务视图-存储>存储桶声明", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>存储桶", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>卷快照", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>pvc告警相关", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>minio对象存储", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "业务视图-应用管理>模板应用", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-应用管理>组件应用", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>定时任务", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>任务", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "独立视图-Catalog(应用商店)", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-镜像仓库", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "平台管理-应用商店管理>Operator", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "平台管理-应用商店管理>模板仓库", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "平台管理-应用商店管理>应用包管理", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "平台管理-应用商店管理>应用商店chart/operator支持ip协议过滤", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "独立视图-云边协同应用下发", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-GitOps应用(项目级别)", "user": "xfzhao", "size": 0, "detail": []},
     ]
     }
]
