en_chs = {"Jingnan Shi": "史京南", "Ke Wang": "王珂", "Yuan Shi": "施源", "Mingyu Liu": "刘明宇",
          "Xiaofeng Zhao": "赵晓峰", "Junlei Li": "李俊磊", "Ya Wei": "魏娅", "Zhongxiu Zhang": "张仲秀"}
mentions = {"Jingnan Shi": "jnshi", "Ke Wang": "kewang", "Yuan Shi": "yuanshi", "Mingyu Liu": "myliu",
            "Xiaofeng Zhao": "xfzhao", "Junlei Li": "jlli", "Ya Wei": "yawei", "Zhongxiu Zhang": "zxzhang"}
jira_user_features = [
    {"Zhongxiu Zhang": ['ACP - 命名空间概览', 'ACP - 命名空间管理', 'ACP - 联邦命名空间管理', 'ACP - 应用管理 - 联邦应用', 'ACP - Workload管理', 'ACP - 配置管理', 'ACP - GPU', 'ACP - 自定义资源定义']},
    {"Jingnan Shi": ['ACP - 集群管理 - 资源管理', 'ACP - 辅助功能', 'ACP - 安全管理 - 节点隔离策略', 'ACP - 应用管理 - OAM应用', 'ACP - 应用管理 - 原生应用']},
    {"Ke Wang": ['ACP - 网络管理 - OVN', 'ACP - 网络管理 - 负载均衡', 'ACP - 网络管理 - GatewayAPI', 'ACP - 网络管理 - 网络监测', 'ACP - 网络管理 - 集群网络策略']},
    {"Yuan Shi": ['ACP - 网络管理 - CALICO', 'ACP - 网络管理 - Flannel', 'ACP - 网络管理 - 域名证书', 'ACP - 网络管理 - SVC/Ingress', 'ACP - 网络管理 - 外部路由', 'ACP - 虚拟化管理']},
    {"Mingyu Liu": ['ACP - 存储管理 - PV/PVC/StorageClass', 'ACP - 存储管理 - Rook-Ceph', 'ACP - 存储管理 - Topolvm', 'ACP - 存储管理 - 对接外部存储', 'ACP - 存储管理 - Minio', 'ACP - 超售比',
                    'ACP - 功能开关']},
    {"Xiaofeng Zhao": ['ACP - 应用商店管理 - 模板管理', 'ACP - 应用商店管理 - Operator', 'ACP - 应用商店管理 - 应用包管理', 'ACP - 应用商店 - 通用功能', 'ACP - 应用商店 - DockerRegistry',
                       'ACP - 应用商店 - ChartMuseum', 'ACP - 应用管理 - 组件应用', 'ACP - 应用管理 - 模板应用', 'ACP - 镜像仓库', 'ACP - 定时任务管理', 'ACP - GitOps应用', 'ACP - 云边协同']}
]
# importance "high_detail": [], "low_detail": []
# keyword   "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []    "error_total": 0
# status  "size": 0, "detail": []   "total": 0
func_suite_assign = [
    {"user": "史京南", "error_total": 0, "total": 0,
     "suites": [
         {"suitename": "业务视图-OAM 应用", "user": "jnshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-原生应用", "user": "jnshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-安全管理", "user": "jnshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-集群管理-资源管理", "user": "jnshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-辅助功能", "user": "jnshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "etcd监控面板", "user": "jnshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []}
     ]
     },
    {"user": "赵晓峰", "error_total": 0, "total": 0,
     "suites": [
         {"suitename": "业务视图-应用管理>模板应用", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-应用管理>组件应用", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>定时任务", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>任务", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "独立视图-Catalog(应用商店)", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-镜像仓库", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-应用商店管理>Operator", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-应用商店管理>模板仓库", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-应用商店管理>应用包管理", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-应用商店管理>应用商店chart/operator支持ip协议过滤", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "独立视图-云边协同应用下发", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-GitOps应用(项目级别)", "user": "xfzhao", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
     ]
     },
    {"user": "张仲秀", "error_total": 0, "total": 0,
     "suites": [
         {"suitename": "业务视图-计算组件>部署", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>守护进程集", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>有状态副本集", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>容器组", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>弹性伸缩", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>通用-镜像选择组件", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>通用-容器组表单", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>通用-详情页组件", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>通用-容器组列表", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>通用-局部更新", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>通用-debug", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>gpu", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>通用-取消-阻断性提示", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [], "error_size": 0,
          "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-计算组件>asm-acp融合", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-配置", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-超售比", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "项目管理-命名空间>命名空间", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "项目管理-命名空间>命名空间概览", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-集群管理-自定义资源", "user": "zxzhang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
     ]
     },
    {"user": "施源", "error_total": 0, "total": 0,
     "suites": [
         {"suitename": "业务视图-网络>内部路由", "user": "yuanshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-网络>外部路由", "user": "yuanshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-网络>入站规则", "user": "yuanshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-网络管理>域名", "user": "yuanshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-网络管理>证书", "user": "yuanshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-网络管理>子网>calico", "user": "yuanshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-虚拟化", "user": "yuanshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-虚拟化管理", "user": "yuanshi", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
     ]
     },
    {"user": "王珂", "error_total": 0, "total": 0,
     "suites": [
         {"suitename": "业务视图-网络>负载均衡", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-网络>网络策略", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-网络>alb集成GatewayAPI", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [], "error_size": 0,
          "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-网络管理>负载均衡", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-网络管理>负载均衡器-重构用例", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-网络管理>子网>ovn", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-网络管理>集群网络策略", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-网络管理>外部地址池", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-ovn集群互通管理", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-kubeOVN网络可视化", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-网络管理>网络检测", "user": "kewang", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
     ]
     },
    {"user": "刘明宇", "error_total": 0, "total": 0,
     "suites": [
         {"suitename": "功能开关", "user": "myliu", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-存储>持久卷声明", "user": "myliu", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-存储管理>持久卷", "user": "myliu", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-存储管理>存储类", "user": "myliu", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-存储管理>分布式存储", "user": "myliu", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-存储管理>本地存储", "user": "myliu", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "业务视图-存储> 存储桶声明", "user": "myliu", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-存储管理>存储桶", "user": "myliu", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
         {"suitename": "平台管理-存储管理>卷快照", "user": "myliu", "high_detail": [], "low_detail": [], "size": 0, "detail": [],
          "error_size": 0, "error_smoke": [], "high_smoke": [], "api": []},
     ]
     }
]
api_suite_assign = [
    {"user": "史京南", "total": 0,
     "suites": [
         {"suitename": "业务视图-OAM 应用", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "业务视图-原生应用", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "平台管理-安全管理", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "平台管理-集群管理-资源管理", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "业务视图-辅助功能", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "etcd监控面板", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>部署", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>守护进程集", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>有状态副本集", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>容器组", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>弹性伸缩", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-镜像选择组件", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-容器组表单", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-详情页组件", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-容器组列表", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-局部更新", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-debug", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>gpu", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-取消-阻断性提示", "user": "zxzhang", "size": 0, "detail": []},
         # {"suitename": "业务视图-计算组件>asm-acp融合", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-配置", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "平台管理-超售比", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "项目管理-命名空间", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "平台管理-集群管理-自定义资源", "user": "zxzhang", "size": 0, "detail": []},
     ]
     },
    {"user": "赵晓峰",
     "total": 0,
     "suites": [
         {"suitename": "业务视图-应用管理>模板应用", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-应用管理>组件应用", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>定时任务", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>任务", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "独立视图-Catalog(应用商店)", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-镜像仓库", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "平台管理-应用商店管理>Operator", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "平台管理-应用商店管理>模板仓库", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "平台管理-应用商店管理>应用包管理", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "平台管理-应用商店管理>应用商店chart/operator支持ip协议过滤", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "独立视图-云边协同应用下发", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-GitOps应用(项目级别)", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-存储>持久卷声明", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>持久卷", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>存储类", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>分布式存储", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>本地存储", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "业务视图-存储> 存储桶声明", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>存储桶", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>卷快照", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>pvc告警相关", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>minio对象存储", "user": "myliu", "size": 0, "detail": []},
     ]
     },
    {"user": "施源", "total": 0,
     "suites": [
         {"suitename": "业务视图-网络>内部路由", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "业务视图-网络>外部路由", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "业务视图-网络>入站规则", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>域名", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>证书", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>子网>calico", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "业务视图-虚拟化", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "平台管理-虚拟化管理", "user": "yuanshi", "size": 0, "detail": []},
     ]
     },
    {"user": "王珂", "total": 0,
     "suites": [
         {"suitename": "业务视图-网络>负载均衡", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "业务视图-网络>网络策略", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "业务视图-网络>alb集成GatewayAPI", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>负载均衡", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>负载均衡器-重构用例", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>子网>ovn", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>集群网络策略", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>外部地址池", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-ovn集群互通管理", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-kubeOVN网络可视化", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>网络检测", "user": "kewang", "size": 0, "detail": []},
     ]
     },
]
ui_suite_assign = [
    {"user": "史京南", "total": 0,
     "suites": [
         {"suitename": "业务视图-OAM 应用", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "业务视图-原生应用", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "平台管理-安全管理", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "平台管理-集群管理-资源管理", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "业务视图-辅助功能", "user": "jnshi", "size": 0, "detail": []},
         {"suitename": "etcd监控面板", "user": "jnshi", "size": 0, "detail": []}
     ]
     },
    {"user": "张仲秀", "total": 0,
     "suites": [
         {"suitename": "业务视图-计算组件>部署", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>守护进程集", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>有状态副本集", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>容器组", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>弹性伸缩", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-镜像选择组件", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-容器组表单", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-详情页组件", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-容器组列表", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-局部更新", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-debug", "user": "zxzhang", "size": 0, "detail": []},
         # {"suitename": "业务视图-计算组件>gpu", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>通用-取消-阻断性提示", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>asm-acp融合", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "业务视图-配置", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "平台管理-超售比", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "项目管理-命名空间", "user": "zxzhang", "size": 0, "detail": []},
         {"suitename": "平台管理-集群管理-自定义资源", "user": "zxzhang", "size": 0, "detail": []},
     ]
     },
    {"user": "施源", "total": 0,
     "suites": [
         {"suitename": "业务视图-网络>内部路由", "user": "yuanshi", "size": 0, "detail": []},
         # {"suitename": "业务视图-网络>外部路由", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "业务视图-网络>入站规则", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>域名", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>证书", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>子网>calico", "user": "yuanshi", "size": 0, "detail": []},
         # {"suitename": "业务视图-虚拟化", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "平台管理-虚拟化管理", "user": "yuanshi", "size": 0, "detail": []},
         {"suitename": "业务视图-网络>负载均衡", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>负载均衡", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>负载均衡器-重构用例", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>子网>ovn", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>集群网络策略", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-ovn集群互通管理", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-kubeOVN网络可视化", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>网络检测", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "业务视图-网络>网络策略", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "平台管理-网络管理>外部地址池", "user": "kewang", "size": 0, "detail": []},
         {"suitename": "业务视图-网络>alb集成GatewayAPI", "user": "kewang", "size": 0, "detail": []},
     ]
     },
    {"user": "刘明宇", "total": 0,
     "suites": [
         # {"suitename": "功能开关", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "业务视图-存储>持久卷声明", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>持久卷", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>存储类", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>分布式存储", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>本地存储", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "业务视图-存储>存储桶声明", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>存储桶", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>卷快照", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>pvc告警相关", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "平台管理-存储管理>minio对象存储", "user": "myliu", "size": 0, "detail": []},
         {"suitename": "业务视图-应用管理>模板应用", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-应用管理>组件应用", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>定时任务", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-计算组件>任务", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "独立视图-Catalog(应用商店)", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-镜像仓库", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "平台管理-应用商店管理>Operator", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "平台管理-应用商店管理>模板仓库", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "平台管理-应用商店管理>应用包管理", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "平台管理-应用商店管理>应用商店chart/operator支持ip协议过滤", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "独立视图-云边协同应用下发", "user": "xfzhao", "size": 0, "detail": []},
         {"suitename": "业务视图-GitOps应用(项目级别)", "user": "xfzhao", "size": 0, "detail": []},
     ]
     }
]
